name: Generate 3D Contribution Profile

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-3d-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate 3D contribution profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: janvi100104

      - name: Commit generated 3D profile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(profile): update 3d contribution graph"
          file_pattern: profile-3d-contrib/*.svg
